Added Attachments
JustAPenguin9/Akyuu-bot pull request #102
Opened 2024-06-30 04:09 UTC by SonofGod1998

This commit has Byakuren, Doremy, Futo, Ichirin, Joon and Kasen added their attachments

2024-07-01 02:56 UTC, JustAPenguin9 requested changes
doremy, futo, ichirin, joon, kasen, sql files verified. Only byakuren.sql had an issue.

2024-07-01 02:56 UTC, JustAPenguin9 commented on character-sql/byakuren.sql
>  			"damage": "825"
Missing a `,` at the end of the line.

2024-07-02 01:30 UTC, SonofGod1998 commented
I swear I'll finish Nitori's attachments, but please fix Miko's Red Cape 🙏

2024-07-04 09:03 UTC, SonofGod1998 commented
I have FINALLY added Reimu, finished up Nitori and did everything that was on the wiki for Mokou. I should've gone to bed .-.

2024-07-05 21:57 UTC, JustAPenguin9 approved these changes

2024-07-12 02:37 UTC, merged

2024-07-12 02:58 UTC, JustAPenguin9 commented
The remaining characters are filed under issue #103